We don't need another copy of README.md in the container

diff --git a/hack/run_test b/hack/run_test
--- a/hack/run_test
+++ b/hack/run_test
@@ -501,25 +501,24 @@ $volume_options
 
 run_doc_test() {
   local tmpdir=$(mktemp -d)
+  local f
   echo "  Testing documentation in the container image"
   # Extract the help files from the container
-  for f in help.md help.1 ; do
-    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/${f}
+  for f in /usr/share/container-scripts/postgresql/README.md help.1 ; do
+    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/$(basename ${f})
+    # Check whether the files include some important information
+    for term in POSTGRESQL_ADMIN_PASSWORD volume 5432 ; do
+      if ! cat ${tmpdir}/$(basename ${f}) | grep -q -e "${term}" ; then
+        echo "ERROR: File /${f} does not include '${term}'."
+        return 1
+      fi
+    done
   done
   # Check whether the files use the correct format
   if ! file ${tmpdir}/help.1 | grep -q roff ; then
     echo "ERROR: /help.1 is not in troff or groff format"
     return 1
   fi
-  # Check whether the files include some important information
-  for term in POSTGRESQL_ADMIN_PASSWORD volume 5432 ; do
-    for f in help.md help.1 ; do
-      if ! cat ${tmpdir}/${f} | grep -q -e "${term}" ; then
-        echo "ERROR: File /${f} does not include '${term}'."
-        return 1
-      fi
-    done
-  done
   echo "  Success!"
   echo
 }
