Add help.1 file
Atomic CLI tool shows groff formatted man page if called by atomic help <img>, so all images should support it.
Currently the man page is generated outside of the build system by pandoc -s -f markdown -t man.

diff --git a/hack/run_test b/hack/run_test
--- a/hack/run_test
+++ b/hack/run_test
@@ -498,6 +498,31 @@ $volume_options
   echo "  Success!"
 }
 
+run_doc_check() {
+  local tmpdir=$(mktemp -d)
+  echo "  Testing documentation in the container image"
+  # Extract the help files from the container
+  for f in help.md help.1 ; do
+    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/${f}
+  done
+  # Check whether the files use the correct format
+  if ! file ${tmpdir}/help.1 | grep -q roff ; then
+    echo "ERROR: /help.1 is not in troff or groff format"
+    return 1
+  fi
+  # Check whether the files include some important information
+  for term in POSTGRESQL_ADMIN_PASSWORD volume 5432 ; do
+    for f in help.md help.1 ; do
+      if ! cat ${tmpdir}/${f} | grep -q -e "${term}" ; then
+        echo "ERROR: File /${f} does not include '${term}'."
+        return 1
+      fi
+    done
+  done
+  echo "  Success!"
+  echo
+}
+
 function run_general_tests() {
   PGUSER=user PASS=pass POSTGRESQL_MAX_CONNECTIONS=42 POSTGRESQL_MAX_PREPARED_TRANSACTIONS=42 POSTGRESQL_SHARED_BUFFERS=64MB run_tests no_admin
   PGUSER=user1 PASS=pass1 ADMIN_PASS=r00t run_tests admin
@@ -506,6 +531,7 @@ function run_general_tests() {
   DOCKER_ARGS="-u 12345" PGUSER=user2 PASS=pass run_tests no_admin_altuid
   DOCKER_ARGS="-u 12345" PGUSER=user3 PASS=pass1 ADMIN_PASS=r00t run_tests admin_altuid
   DB=postgres DOCKER_ARGS="-u 12345" ADMIN_PASS=rOOt run_tests only_admin_altuid
+  run_doc_check
 }
 
 function run_all_tests() {
